<?php

namespace JourEtMenu\JourEtMenuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntreesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreesRepository extends EntityRepository
{
}
