<?php

namespace JourEtMenu\JourEtMenuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FormulesJourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulesJourRepository extends EntityRepository
{
}
