<?php

namespace JourEtMenu\JourEtMenuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenusRepository extends EntityRepository
{

	public function byRestaurant($utilisateur) {
		$qb = $this->createQueryBuilder('u')
		->select('u')
		->where('u.restaurant = :utilisateur')
		->orderBy('u.id','DESC')
		->setParameter('utilisateur', $utilisateur);
		return $qb->getQuery()->getResult();
	}
}
